pipeline {
  agent any
    tools {
      gradle 'gradle 7.2'
                 jdk 'JDK11'
    }
    stages {      
        stage('Build with Gradle') {
            steps { 
                    sh 'pwd'      
                    sh './gradlew clean build'
            }
        }
        
        stage('Copy Artifact') {
           steps { 
                   sh 'pwd'
		   sh 'cp -r target/*.jar docker'
           }
        }
         
        stage('Build docker image') {
           steps {
               script {         
                 def customImage = docker.build('project/doogeun', "./docker")
                 docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                 customImage.push("${env.BUILD_NUMBER}")
                 }                     
           }
        }
	  }
    }
}
